---
title: "R Notebook"
output: html_notebook
---



```{r}
library(dplyr)
library(tidyverse)

```

```{r}
df <- read.csv("/Users/rhalenathomas/Documents/Data/scRNAseq/ParseExample/Experiment1-mini12/SumCounts_Integrated_by_sample_celltype.csv")
```

Reformat to separate the Cell type, Line and Batch

```{r}
# Assuming your original dataframe is called 'df'
# Extract variables from column names

df[1:5,1:6]

variables <- strsplit(colnames(df), "_")

# Create new dataframe with genes as rows and variables as columns
new_df <- data.frame(Gene = rownames(df), Celltype = character(nrow(df)), Line = character(nrow(df)), Batch = character(nrow(df)), stringsAsFactors = FALSE)

# Iterate over each column in the original dataframe
for (i in 1:length(variables)) {
  # Handle different patterns in column names
  if (length(variables[[i]]) == 1) {
    # Handle case where only Celltype is present
    new_df$Celltype <- variables[[i]][1]
  } else if (length(variables[[i]]) == 2) {
    # Handle case where Celltype and Line are present
    if (grepl("B", variables[[i]][2])) {
      split_values <- strsplit(variables[[i]][2], "B")
      new_df$Celltype <- variables[[i]][1]
      new_df$Line <- split_values[[1]][1]
      new_df$Batch <- split_values[[1]][2]
    } else {
      new_df$Celltype <- variables[[i]][1]
      new_df$Line <- variables[[i]][2]
    }
  } else if (length(variables[[i]]) == 3) {
    # Handle case where Celltype, Line, and Batch are present
    new_df$Celltype <- variables[[i]][1]
    new_df$Line <- variables[[i]][2]
    new_df$Batch <- variables[[i]][3]
  }
}

# Display the transformed dataframe
new_df[1:3,1:4]


```



